version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3002:80"
    env_file:
      - ./frontend/.env
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
